version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
        - app
    container_name: avtourist-nginx


  app:
    #image: php:8.3-fpm
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
        - db
    container_name: avtourist-app

  db:
    image: mysql:8.2
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: avtourist
      MYSQL_ROOT_PASSWORD: "root_pass"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "pass"
    ports:
      - "8101:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: avtourist-db
